deployment:
  tasks:
    - export DEPLOYPATH=/home/jt30e3li9al4/public_html/xn--dermocan-g1a.com/
    # Copy files from the repo folder to the public folder
    # -R preserves structure, -u updates only newer files (safer)
    - /bin/cp -R * $DEPLOYPATH
    # Fix Permissions
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;